UniMath/TypeTheory

TypeTheory/Displayed_Cats/.package/files
TypeTheory/Displayed_Cats/README.md
TypeTheory/Displayed_Cats/SIP.v

Proof of the Structure Identity Principle

---

TypeTheory/Auxiliary/Auxiliary.v

fix compilation errors due to changes in UniMath/UniMath

---

TypeTheory/ALV1/RelUnivYonedaCompletion.v
TypeTheory/ALV1/RelativeUniverses.v
TypeTheory/Auxiliary/Auxiliary.v
TypeTheory/Displayed_Cats/Auxiliary.v
TypeTheory/Displayed_Cats/Constructions.v

adapt to latest UniMath/UniMath

---

Makefile

... by uncommenting the rules for making it.

make "make TAGS" work again

---

TypeTheory/Displayed_Cats/Codomain.v
TypeTheory/Displayed_Cats/ComprehensionC.v

Towards comprehension cat from c w DM

---

TypeTheory/ALV1/CwF_SplitTypeCat_Cats_Standalone.v
TypeTheory/ALV1/CwF_SplitTypeCat_Equivalence.v
TypeTheory/ALV1/CwF_SplitTypeCat_Maps.v
TypeTheory/ALV1/RelativeUniverses.v
TypeTheory/ALV2/CwF_SplitTypeCat_Cats.v
TypeTheory/ALV2/CwF_SplitTypeCat_Univalent_Cats.v
TypeTheory/Auxiliary/Auxiliary.v
TypeTheory/Categories/category_FAM.v
TypeTheory/Displayed_Cats/Constructions.v
TypeTheory/Displayed_Cats/Core.v
TypeTheory/Displayed_Cats/Equivalences.v
TypeTheory/Displayed_Cats/Fibrations.v
TypeTheory/OtherDefs/CwF_1.v
TypeTheory/OtherDefs/CwF_Pitts.v
TypeTheory/OtherDefs/DM.v

adapt to latest unimath

---

TypeTheory/Displayed_Cats/ComprehensionC.v
TypeTheory/Displayed_Cats/Core.v

A simple dualization of an existing lemma.

postcomp with disp iso is equivalence

---

TypeTheory/Auxiliary/Auxiliary.v
TypeTheory/Displayed_Cats/Equivalences.v

needed because of changes to adjunctions in UniMath

fix compilation

---

TypeTheory/Displayed_Cats/Fibrations.v

still missing: proof of univalence of the cat of disc fibs

finished equivalence of precats between disc fibs and presheaves

---

TypeTheory/Displayed_Cats/Equivalences.v

add definitions for disp adjunctions and disp (sloppy) equivalences

---

TypeTheory/ALV1/.package/files
TypeTheory/ALV1/CwF_def.v
TypeTheory/ALV1/RepMaps.v

- put representable maps into their own file
- add references for cwf à la Fiore and for rep. maps in headers

Small reorg of file on cwfs

---

.travis.yml
TypeTheory/Auxiliary/Auxiliary.v
TypeTheory/Displayed_Cats/.package/files
TypeTheory/Displayed_Cats/Equivalences.v
TypeTheory/Displayed_Cats/Equivalences_bis.v
TypeTheory/Displayed_Cats/Examples.v

- keep the file on those things over identity functor, since compile time is shockingly slow for general defs
- includes fix to compile with latest unimath

start working on general displayed adjunctions, equivalences etc

---

TypeTheory/ALV1/CwF_def.v
TypeTheory/ALV1/RelUnivYonedaCompletion.v
TypeTheory/ALV1/RelativeUniverses.v
TypeTheory/ALV1/RepMaps.v
TypeTheory/Auxiliary/Auxiliary.v

- definition of a "mere relative universe structure"
- construction of an equivalence between "mere relative universes" and representable maps of presheaves
- transfer of "mere relative universes" along two functors, analogous to the transfer of non-truncated stuff

On representable maps of presheaves

---

TypeTheory/ALV1/.package/files
TypeTheory/ALV1/TypeCat.v
TypeTheory/ALV1/TypeCat_Reassoc.v
TypeTheory/Auxiliary/Auxiliary.v
TypeTheory/OtherDefs/.package/files
TypeTheory/OtherDefs/CwF_Pitts_to_DM.v
TypeTheory/OtherDefs/CwF_Pitts_to_TypeCat.v
TypeTheory/OtherDefs/CwF_Pitts_to_TypeCat_to_DM.v
TypeTheory/OtherDefs/DM_to_TypeCat.v
TypeTheory/OtherDefs/DM_to_TypeCat_to_DM.v
TypeTheory/OtherDefs/TypeCat_to_CwF_Pitts.v
TypeTheory/OtherDefs/TypeCat_to_DM.v

work done by PLL, hidden in old branch

standalone definition of split type structure and equivalence to Sigma obj-ext q-mor

---

TypeTheory/ALV1/CwF_SplitTypeCat_Cats_Standalone.v
TypeTheory/ALV1/CwF_SplitTypeCat_Defs.v
TypeTheory/ALV1/CwF_SplitTypeCat_Equivalence.v
TypeTheory/ALV1/CwF_SplitTypeCat_Maps.v
TypeTheory/ALV1/TypeCat.v
TypeTheory/ALV1/TypeCat_Reassoc.v
TypeTheory/ALV2/CwF_SplitTypeCat_Equiv_Cats.v
TypeTheory/Auxiliary/Auxiliary.v
TypeTheory/OtherDefs/CwF_Pitts_to_TypeCat.v
TypeTheory/OtherDefs/DM_to_TypeCat.v
TypeTheory/OtherDefs/TypeCat_to_CwF_Pitts.v
TypeTheory/OtherDefs/TypeCat_to_DM.v

Consistentised the directions of equalities and pullbacks between different definitions of type-categories; and completed the equivalence between the two versions of type categories

Remove last outstanding admit!

---

TypeTheory/ALV1/CwF_Defs_Equiv.v
TypeTheory/ALV1/CwF_SplitTypeCat_Defs.v
TypeTheory/ALV1/CwF_SplitTypeCat_Equivalence.v
TypeTheory/ALV1/CwF_SplitTypeCat_Maps.v
TypeTheory/ALV1/CwF_def.v
TypeTheory/ALV1/RelUnivYonedaCompletion.v
TypeTheory/ALV1/RelativeUniverses.v
TypeTheory/ALV1/RepMaps.v
TypeTheory/ALV1/Summary.v
TypeTheory/ALV1/Transport_along_Equivs.v

for equivalence between split typecat structures and cwf structures

added stuff to summary

---

TypeTheory/ALV1/RelativeUniverses.v

and the fact that this is an equivalence when...

forgetful function from relative universes to relative weak universes

---

TypeTheory/Articles/ALV_2017.v

added construction of equivalence between rep(C) and cwf(RC(C))

---

.travis.yml
TypeTheory/Displayed_Cats/Examples.v

using @cathlelay 's code from UniMath 
closes #81

disp precategory of topological spaces

---

TypeTheory/Displayed_Cats/ComprehensionC.v
TypeTheory/Displayed_Cats/DisplayedCatFromCwDM.v
TypeTheory/Displayed_Cats/Examples.v
TypeTheory/Displayed_Cats/Fibrations.v

Fibrations

---

TypeTheory/Displayed_Cats/Codomain.v
TypeTheory/Displayed_Cats/ComprehensionC.v

add implication cartesian to isPullback

---

TypeTheory/ALV1/CwF_SplitTypeCat_Cats_Standalone.v
TypeTheory/ALV1/CwF_SplitTypeCat_Equivalence.v
TypeTheory/ALV1/CwF_def.v
TypeTheory/ALV1/RelUnivYonedaCompletion.v
TypeTheory/ALV1/RelativeUniverses.v
TypeTheory/ALV1/RepMaps.v
TypeTheory/ALV1/Transport_along_Equivs.v
TypeTheory/ALV1/TypeCat_Reassoc.v
TypeTheory/ALV2/CwF_SplitTypeCat_Equiv_Comparison.v
TypeTheory/ALV2/CwF_SplitTypeCat_Univalent_Cats.v
TypeTheory/Articles/ALV_2017.v
TypeTheory/Auxiliary/Auxiliary.v
TypeTheory/Categories/category_FAM.v
TypeTheory/Categories/category_of_elements.v
TypeTheory/Displayed_Cats/Constructions.v
TypeTheory/Displayed_Cats/Core.v
TypeTheory/Displayed_Cats/Fibrations.v
TypeTheory/Displayed_Cats/SIP.v
TypeTheory/OtherDefs/CwF_Pitts_completion.v
TypeTheory/OtherDefs/CwF_Pitts_to_DM.v
TypeTheory/OtherDefs/CwF_Pitts_to_TypeCat_to_DM.v
TypeTheory/OtherDefs/DM.v
TypeTheory/OtherDefs/DM_to_TypeCat_to_DM.v
TypeTheory/OtherDefs/TypeCat_to_DM.v

This PR is incomplete in that it does not rename some identifiers.
It does, however, compile.

adapt to vocabulary change in UniMath/UniMath (see #701)

---

TypeTheory/ALV1/CwF_Defs_Equiv.v
TypeTheory/ALV1/CwF_SplitTypeCat_Cats_Standalone.v
TypeTheory/ALV1/CwF_SplitTypeCat_Defs.v
TypeTheory/ALV1/CwF_SplitTypeCat_Equivalence.v
TypeTheory/ALV1/CwF_SplitTypeCat_Maps.v
TypeTheory/ALV1/CwF_def.v
TypeTheory/ALV1/RelUnivYonedaCompletion.v
TypeTheory/ALV1/RelativeUniverses.v
TypeTheory/ALV1/RepMaps.v
TypeTheory/ALV1/Transport_along_Equivs.v
TypeTheory/ALV1/TypeCat_Reassoc.v
TypeTheory/ALV2/CwF_SplitTypeCat_Cats.v
TypeTheory/ALV2/CwF_SplitTypeCat_Equiv_Cats.v
TypeTheory/ALV2/CwF_SplitTypeCat_Equiv_Comparison.v
TypeTheory/ALV2/CwF_SplitTypeCat_Univalent_Cats.v
TypeTheory/Articles/ALV_2017.v
TypeTheory/Auxiliary/Auxiliary.v
TypeTheory/Displayed_Cats/Auxiliary.v
TypeTheory/Displayed_Cats/Codomain.v
TypeTheory/Displayed_Cats/ComprehensionC.v
TypeTheory/Displayed_Cats/Constructions.v
TypeTheory/Displayed_Cats/Core.v
TypeTheory/Displayed_Cats/DisplayedCatFromCwDM.v
TypeTheory/Displayed_Cats/Equivalences.v
TypeTheory/Displayed_Cats/Equivalences_bis.v
TypeTheory/Displayed_Cats/Examples.v
TypeTheory/Displayed_Cats/Fibrations.v
TypeTheory/Displayed_Cats/Limits.v
TypeTheory/Displayed_Cats/SIP.v
TypeTheory/OtherDefs/TypeCat_to_CwF_Pitts.v

response to https://github.com/UniMath/UniMath/pull/702

rename 'Precategory' -> 'category'

---

TypeTheory/ALV1/TypeCat.v
TypeTheory/Auxiliary/Auxiliary.v
TypeTheory/Auxiliary/CategoryTheoryImports.v
TypeTheory/Auxiliary/UnicodeNotations.v
TypeTheory/Categories/category_FAM.v
TypeTheory/Categories/ess_and_gen_alg_cats.v
TypeTheory/Displayed_Cats/Auxiliary.v
TypeTheory/Displayed_Cats/Codomain.v
TypeTheory/Displayed_Cats/ComprehensionC.v
TypeTheory/Displayed_Cats/Constructions.v
TypeTheory/Displayed_Cats/Core.v
TypeTheory/Displayed_Cats/DisplayedCatFromCwDM.v
TypeTheory/Displayed_Cats/Equivalences.v
TypeTheory/Displayed_Cats/Equivalences_bis.v
TypeTheory/Displayed_Cats/Examples.v
TypeTheory/Displayed_Cats/Fibrations.v
TypeTheory/Displayed_Cats/Limits.v
TypeTheory/Displayed_Cats/SIP.v
TypeTheory/OtherDefs/DM.v

rename `precategories.v` -> `Categories.v`

adapt to changes in UniMath/UniMath

---

Makefile
TypeTheory/Csystems/.package/files
TypeTheory/Csystems/hSet_ltowers.v
TypeTheory/Csystems/lC0systems.v
TypeTheory/Csystems/lCsystems.v
TypeTheory/Csystems/lTowers.v
TypeTheory/Csystems/ltowers_over.v
TypeTheory/Csystems/prelim.v

with proofs repaired by @rmatthes

Some of VV's C-systems material

---

Makefile
TypeTheory/.dir-locals.el
TypeTheory/ALV1/TypeCat_Reassoc.v
TypeTheory/Auxiliary/Auxiliary.v
TypeTheory/Categories/category_FAM.v

- Makefile did not pass all necessary arguments to coqc
- renaming of `gradth`

adapt to changes in infrastructure, Coq, and UniMath

---

TypeTheory/ALV1/RelativeUniverses.v

requires
- functor fully faithful
- both categories' hom-types are sets

Functorial structure on a rel univ is a proposition

---

TypeTheory/Csystems/lC0systems.v
TypeTheory/Csystems/lCsystems.v

This follows a suggestion by Benedikt.
The PR is ready to be integrated into master.

equation on ft of f^* now turned into iso, not just a morphism

---

TypeTheory/Csystems/lC0systems.v
TypeTheory/Csystems/lCsystems.v

This tries to formalize a proposition in the first C-systems paper by VV.
Currently, I am struggling with showing that g can be calculated from its father and its composition with q. The part that is shown on paper is already fine, but there is a subtle type dependency that I do not get rid of.
Not yet a real PR.

try to prove that C-systems have pullback diagrams for q

---

TypeTheory/ALV1/TypeCat.v
TypeTheory/Auxiliary/CategoryTheoryImports.v
TypeTheory/Categories/category_FAM.v
TypeTheory/Categories/category_of_elements.v
TypeTheory/Categories/ess_and_gen_alg_cats.v
TypeTheory/Csystems/lC0systems.v
TypeTheory/Csystems/lCsystems.v
TypeTheory/Cubical/FillFromComp.v
TypeTheory/Displayed_Cats/ComprehensionC.v
TypeTheory/Displayed_Cats/DisplayedCatFromCwDM.v
TypeTheory/Instances/Presheaves.v
TypeTheory/OtherDefs/CwF_1.v
TypeTheory/OtherDefs/CwF_Pitts.v
TypeTheory/OtherDefs/CwF_Pitts_completion.v
TypeTheory/OtherDefs/CwF_Pitts_to_DM.v
TypeTheory/OtherDefs/DM.v
TypeTheory/OtherDefs/DM_to_TypeCat_to_DM.v

take into account the restructuring of the UniMath library

update import statements to make the package compile

---

.travis.yml
Makefile
TypeTheory/ALV1/CwF_SplitTypeCat_Equivalence.v
TypeTheory/ALV1/TypeCat.v
TypeTheory/Auxiliary/.package/files
TypeTheory/Auxiliary/Auxiliary.v
TypeTheory/Auxiliary/CategoryTheoryImports.v
TypeTheory/Auxiliary/Partial.v
TypeTheory/Categories/category_FAM.v
TypeTheory/Initiality/.package/files
TypeTheory/Initiality/Environments.v
TypeTheory/Initiality/Initiality.v
TypeTheory/Initiality/Interpretation.v
TypeTheory/Initiality/InterpretationLemmas.v
TypeTheory/Initiality/SplitTypeCat_Contextual.v
TypeTheory/Initiality/SplitTypeCat_General.v
TypeTheory/Initiality/SplitTypeCat_Maps.v
TypeTheory/Initiality/SplitTypeCat_Structure.v
TypeTheory/Initiality/SyntacticCategory.v
TypeTheory/Initiality/SyntacticCategory_Structure.v
TypeTheory/Initiality/Syntax.v
TypeTheory/Initiality/SyntaxLemmas.v
TypeTheory/Initiality/Typing.v
TypeTheory/Initiality/TypingLemmas.v
TypeTheory/OtherDefs/CwF_Pitts.v
TypeTheory/OtherDefs/TypeCat_to_CwF_Pitts.v

I tried to merge the initiality branch on top of TypeTheory master. It mostly went smoothly, but SyntacticCategory.v does not compile anymore and I don't know what the problems are. They seem to be mostly located in @peterlefanulumsdaine code, so maybe Peter can help me?
For this to work UniMath has to be based on https://github.com/UniMath/UniMath/pull/1192.

WIP on Initiality

---

TypeTheory/Cubical/FillFromComp.v
TypeTheory/Instances/Presheaves.v

transportf_transpose changed to transportf_transpose_right

adapt to upstream changes (in UniMath)

---

.gitignore
.travis.yml
Makefile
TypeTheory/ALV1/CwF_Defs_Equiv.v
TypeTheory/Initiality/Typing.v

We fix a few things so everything will work under the latest version of UniMath, and we modify the travis script so it works, too, and always uses the same version of UniMath (which should be periodically updated).
Resolves #162

make it work

---

TypeTheory/ALV2/RelUnivTransfer.v
TypeTheory/ALV2/RelUniv_Cat_Simple.v

See #169 for the original PR description.

Another proof that reluniv_functor_with_ess_surj is surjective

---

.travis.yml

fix travis build script

---

TypeTheory/Csystems/hSet_ltowers.v

This solves the problem with continuous integration.

a tiny change to make the file compile again

---

TypeTheory/ALV1/RelativeUniverses.v
TypeTheory/Auxiliary/Auxiliary.v
TypeTheory/Csystems/lCsystems.v
TypeTheory/OtherDefs/TypeCat_to_CwF_Pitts.v

This only takes care of the category argument being then implicit for some lemmas concerning inversion of morphisms.

repair work to accommodate PR #1359 for UniMath

---

TypeTheory/ALV1/CwF_SplitTypeCat_Equivalence.v

only to be applied after merge of the **draft** PR #1364

repairs compilation with UniMath PR #1364 (as of today)

---

TypeTheory/Auxiliary/CategoryTheory.v
TypeTheory/Csystems/lC0systems.v
TypeTheory/Csystems/lCsystems.v

only makes sense on base of PR#1507 of UniMath
I did this part because of my previous acquaintance with the directories Bsystems and Csystems.

the beginning of a recovery after the move from iso to z_iso in UniMath

---

.github/workflows/build-typetheory.yml

add build-dep for Coq

---

TypeTheory/RelUniv/RelUnivTransfer.v

just three occurrences of the typo in one single file
fixes #239

restores compilation after upstream PR#1756

---

TypeTheory/Auxiliary/CategoryTheory.v

This should make this repo compatible with probably-upcoming UniMath/UniMath#1974 , while also remaining compatible with current UniMath/UniMath

fix notation level clash with UniMath#1974
