UniMath/TypeTheory

TypeTheory/ALV1/CwF_def.v

Also some cleanup in `CwF_def.v`

Equivalence between canonical CwF definition and rel univ on Yoneda

---

TypeTheory/ALV1/CwF_def.v

If the underlying category is univalent, the type of representations of a morphism of presheaves is a proposition.

representation is a prop as easy consequence of existing lemma

---

TypeTheory/ALV1/Summary.v

give a commutative square with two sides being isos, the other two being the morphisms of presheaves.

recovering the original morphism of presheaves after Rezk completion

---

TypeTheory/Displayed_Cats/Core.v

previously, html was all italic from that section title on.

fix html section title

---

.travis.yml
TypeTheory/ALV1/CwF_SplitTypeCat_Cats_Standalone.v
TypeTheory/ALV2/CwF_SplitTypeCat_Equiv_Cats.v
TypeTheory/ALV2/CwF_SplitTypeCat_Univalent_Cats.v
TypeTheory/Auxiliary/Auxiliary.v
TypeTheory/Categories/category_FAM.v
TypeTheory/Displayed_Cats/Core.v

Few changes necessary. Most importantly, `apply` sometimes does not work any more, in which case `use` does the job.

Adapt to latest UniMath, which now has eta for pairs

---

TypeTheory/ALV1/.package/files
TypeTheory/ALV1/CwF_RelUnivYoneda.v
TypeTheory/ALV1/CwF_SplitTypeCat_Cats_Standalone.v
TypeTheory/ALV1/CwF_SplitTypeCat_Defs.v
TypeTheory/ALV1/CwF_SplitTypeCat_Equivalence.v
TypeTheory/ALV1/CwF_SplitTypeCat_Maps.v
TypeTheory/ALV1/CwF_def.v
TypeTheory/ALV1/Summary.v
TypeTheory/ALV2/CwF_SplitTypeCat_Cats.v
TypeTheory/ALV2/CwF_SplitTypeCat_Equiv_Cats.v
TypeTheory/ALV2/CwF_SplitTypeCat_Univalent_Cats.v

Switched `term_fun_structure` to have `te` instead of `Q` as basic, so all constructions now use this version.
Major outstanding to-do: equivalence between `cwf_structure` (the canonical standalone definition, from `CwF_def.v`) and `cwf'_structure` (the definition based on object-extension structures, from `CwF_SplitTypeCat_Defs.v`).  Much of this can hopefully be cannibalised from the old `CwF_RelUnivYoneda.v`, which is now otherwise redundant and has been dropped from the build.

Switch everything to te-based definition of CwF’s

---

TypeTheory/ALV1/RepMaps.v

Silly me hadn't noticed that the diagram commutes definitionally on the first, proof-relevant, component: the actual morphism. The proof hence is super easy.

finish commutativity of diagram with cwf and rep-map

---

TypeTheory/ALV1/RelativeUniverses.v
TypeTheory/Auxiliary/Auxiliary.v

- definition of `ff_on_isos` not used for the time being
- replace a redundant hypothesis by the required one: faithful instead of ff

removed redundancy in hypotheses of transfer of mere relative universes

---

TypeTheory/ALV1/CwF_SplitTypeCat_Cats_Standalone.v
TypeTheory/ALV2/CwF_SplitTypeCat_Cats.v
TypeTheory/ALV2/CwF_SplitTypeCat_Equiv_Cats.v
TypeTheory/ALV2/CwF_SplitTypeCat_Univalent_Cats.v
TypeTheory/Displayed_Cats/Codomain.v
TypeTheory/Displayed_Cats/ComprehensionC.v
TypeTheory/Displayed_Cats/Constructions.v
TypeTheory/Displayed_Cats/Core.v
TypeTheory/Displayed_Cats/DisplayedCatFromCwDM.v
TypeTheory/Displayed_Cats/Equivalences.v
TypeTheory/Displayed_Cats/Equivalences_bis.v
TypeTheory/Displayed_Cats/Examples.v
TypeTheory/Displayed_Cats/Fibrations.v
TypeTheory/Displayed_Cats/Limits.v
TypeTheory/Displayed_Cats/SIP.v

- `disp_precat` -> `disp_cat`
- `is_category_disp` -> `is_univalent_disp`
Not yet renamed those identifiers referring to naming in UniMath/UniMath, e.g., `total_precat`.

Renaming different kinds of displayed categories

---

Makefile
TypeTheory/Instances/.package/files
TypeTheory/Instances/Presheaves.v

This PR proves that presheaves on a category C (contravariant functors into HSET) forms a type category. As the collection of types in context Γ don't form an hset it is not possible to instantiate the CwF structure, however all of the other axioms of a CwF have also been formalized.

Presheaves are type categories

---

TypeTheory/ALV1/CwF_SplitTypeCat_Cats_Standalone.v
TypeTheory/ALV1/CwF_SplitTypeCat_Maps.v
TypeTheory/ALV1/RelativeUniverses.v
TypeTheory/ALV1/TypeCat_Reassoc.v
TypeTheory/Auxiliary/Auxiliary.v
TypeTheory/Displayed_Cats/ComprehensionC.v
TypeTheory/Instances/Presheaves.v

replace invocations of mkpair by use tpair, sometimes an extra cbn is needed

repair compilation after withdrawal of Ltac def. mkpair in Foundations

---

TypeTheory/ALV1/CwF_Defs_Equiv.v
TypeTheory/ALV1/CwF_SplitTypeCat_Cats_Standalone.v
TypeTheory/ALV1/CwF_SplitTypeCat_Defs.v
TypeTheory/ALV1/CwF_SplitTypeCat_Equivalence.v
TypeTheory/ALV1/CwF_SplitTypeCat_Maps.v
TypeTheory/ALV1/CwF_def.v
TypeTheory/ALV1/RelativeUniverses.v
TypeTheory/ALV1/TypeCat_Reassoc.v
TypeTheory/ALV2/CwF_SplitTypeCat_Cats.v
TypeTheory/ALV2/CwF_SplitTypeCat_Equiv_Cats.v
TypeTheory/ALV2/CwF_SplitTypeCat_Equiv_Comparison.v
TypeTheory/ALV2/CwF_SplitTypeCat_Univalent_Cats.v

The branch is misnamed, but it started with replacing the newly introduced `refine` for `weq_iso` in #128. No effort was made to replace all `refine` if the subsequent proof had to be changed.

more use of "use" or "exact" in ALV1 and ALV2 in place of "refine"

---

TypeTheory/Bsystems/STid.v
TypeTheory/Bsystems/S_St.v
TypeTheory/Bsystems/S_fun.v
TypeTheory/Bsystems/TS_ST.v
TypeTheory/Bsystems/T_Tt.v
TypeTheory/Bsystems/T_fun.v
TypeTheory/Bsystems/dlt.v
TypeTheory/Bsystems/lB.v
TypeTheory/Bsystems/lB0.v
TypeTheory/Bsystems/lB0_non_unital.v
TypeTheory/Bsystems/lB_carriers.v
TypeTheory/Bsystems/lB_non_unital.v
TypeTheory/Bsystems/lB_to_precat.v
TypeTheory/Bsystems/prelB.v
TypeTheory/Bsystems/prelB_non_unital.v
TypeTheory/Csystems/hSet_ltowers.v
TypeTheory/Csystems/lC0systems.v
TypeTheory/Csystems/lCsystems.v
TypeTheory/Csystems/lTowers.v
TypeTheory/Csystems/ltowers_over.v
TypeTheory/Csystems/prelim.v

THIS IS NO PULL REQUEST since the code is not working fine. It is rather a request for help.
Proof General makes a lot of trouble with warnings - PG does not easily go beyond a warning.
There are in particular warnings about notation, starting with the first import statement in prelim.v
Warning: Notation _ ≠ _ was already used in scope nat_scope.
[notation-overridden,parsing]
I then replaced the Require Export by Require Import to have more control since, at some point, the warnings became errors.
I spare you the details if there is a solution to the very first problem that may even make disappear the others.
In any case, the code for B systems imports part of the C-system code, and I did not repair compilation for the B systems that are affected by the lacking export statements.

first try to clean up C systems

---

TypeTheory/Csystems/lC0systems.v
TypeTheory/Instances/Presheaves.v
TypeTheory/OtherDefs/CwF_Pitts_to_DM.v
TypeTheory/OtherDefs/CwF_Pitts_to_TypeCat.v
TypeTheory/OtherDefs/CwF_Pitts_to_TypeCat_to_DM.v
TypeTheory/OtherDefs/DM_to_TypeCat.v
TypeTheory/OtherDefs/DM_to_TypeCat_to_DM.v
TypeTheory/OtherDefs/TypeCat_to_CwF_Pitts.v
TypeTheory/OtherDefs/TypeCat_to_DM.v

just leave out
- `Require Import UniMath.CategoryTheory.total2_paths.`
- wildcards for implicit arguments of `morphism_from_iso`

make the library compile again, after upstream changes in UniMath

---

TypeTheory/Auxiliary/Auxiliary.v
TypeTheory/Cubical/FillFromComp.v
TypeTheory/Instances/Presheaves.v

Auxiliary.v: name of lemma changed
the others need more precise import statements since, otherwise, Δ becomes a notation and cannot be used as variable name

tiny changes to make it compile again after changes in UniMath

---

TypeTheory/ALV1/RelativeUniverses.v
TypeTheory/ALV2/RelUnivTransfer.v
TypeTheory/ALV2/RelUniv_Cat_Simple.v
TypeTheory/Auxiliary/Auxiliary.v

ALV2 Commuting square of transfer constructions

---

TypeTheory/ALV2/RelUnivTransfer.v
TypeTheory/ALV2/RelUniv_Cat_Simple.v
TypeTheory/ALV2/]

My hypothesis is that we do not need any extra assumptions like AC or univalent C for the functor between RelUniv(J) and RelUniv(J') to be surjective.
Current WIP proof starts with some stronger assumptions which should be relaxed:
Now I have an mapping on objects to go from RelUniv(J') to RelUniv(J) which I should document properly. Proving that it is a right inverse directly is cumbersome, so @peterlefanulumsdaine suggested another approach:
Finally, I plan to

Another proof that reluniv_functor_with_ess_surj issurjective (assuming R is essentially surjective)

---

TypeTheory/ALV2/.package/files
TypeTheory/ALV2/Comprehension_Cats.v
TypeTheory/ALV2/TypeCat_ComprehensionCat.v

Connect type categories with comprehension categories

---

TypeTheory/ALV2/.package/files
TypeTheory/ALV2/FullyFaithfulDispFunctor.v
TypeTheory/ALV2/TypeCat_ComprehensionCat.v

Type categories are equivalent to (full and faithful) comprehension categories

---

TypeTheory/ALV2/.package/files
TypeTheory/ALV2/DiscCompCatDef_Cat.v
TypeTheory/ALV2/DiscCompCatDef_DiscCompCat_catiso.v
TypeTheory/ALV2/DiscCompCat_Cat.v
TypeTheory/ALV2/DiscreteComprehensionCat.v
TypeTheory/ALV2/SplitTypeCat_Cat_Simple.v
TypeTheory/ALV2/SplitTypeCat_DiscCompCatDef_catiso.v
TypeTheory/ALV2/SplitTypeCat_DiscCompCat_catiso.v

This is a follow up of #175 (there we showed an equivalence of types). In this PR we now construct an equivalence of categories where objects are split type cat structures and discrete comprehension cat structures:

Split type categories and discrete comprehension categories (categorically)

---

TypeTheory/Initiality/SplitTypeCat_General.v
TypeTheory/TypeConstructions/.package/files
TypeTheory/TypeConstructions/SplTCwF_TypeFormers.v

This PR formalize :
- a new definition for the "middle structure" in the CwF - SplTC equivalence. This definition doesn't have any "preference" between the term structure and the qq structure and shown to be equivalent to the two others definitions already use in the code.  There is also the access function for this definition and two definitions of term with typing taken into account.
- Sigma Type over that middle structure 
- Pi Type over that middle structure
- Identity Type over that middle structure
- Family of Types over that middle structure
This use a version of term with the internal typing directly taken into account.

Sigma, Pi and Identity Types structure over the "middle structure"

---

.github/workflows/build-typetheory.yml

If this works, it fixes #199, the broken CI build due to expanded (non-linear) package dependencies in UniMath.  To test whether this works, we need to see the CI run on it — hopefully that should happen automatically when this PR is issued.  So this PR should presumably be merged if and only if the CI succeeds!

Added UniMath package dependencies in github workflow, to (hopefully) fix #199

---

TypeTheory/ALV1/CwF_SplitTypeCat_Defs.v
TypeTheory/ALV1/CwF_def.v
TypeTheory/ALV1/RelativeUniverses.v
TypeTheory/ALV1/Transport_along_Equivs.v
TypeTheory/ALV1/TypeCat.v
TypeTheory/ALV2/RelUnivTransfer.v
TypeTheory/ALV2/SplitTypeCat_ComprehensionCat.v
TypeTheory/Auxiliary/Auxiliary.v
TypeTheory/Auxiliary/CategoryTheory.v
TypeTheory/Categories/ess_alg_categories.v
TypeTheory/Categories/ess_and_gen_alg_cats.v
TypeTheory/Cubical/FillFromComp.v
TypeTheory/Displayed_Cats/ComprehensionC.v
TypeTheory/Displayed_Cats/DisplayedCatFromCwDM.v
TypeTheory/OtherDefs/CwF_1.v
TypeTheory/OtherDefs/CwF_Pitts.v
TypeTheory/OtherDefs/CwF_Pitts_completion.v
TypeTheory/OtherDefs/CwF_Pitts_natural.v
TypeTheory/OtherDefs/CwF_Pitts_to_DM.v
TypeTheory/OtherDefs/CwF_Pitts_to_TypeCat.v
TypeTheory/OtherDefs/CwF_Pitts_to_TypeCat_to_DM.v
TypeTheory/OtherDefs/DM.v
TypeTheory/OtherDefs/DM_to_TypeCat.v
TypeTheory/OtherDefs/DM_to_TypeCat_to_DM.v
TypeTheory/OtherDefs/TypeCat_to_DM.v

Following UniMath/UniMath#1402 and #196 , this PR refactors throughout UniMath/TypeTheory to use more of the language of categories, and less of precategories.
I’ve aimed to be light-touch, and generally avoided changing mathematical content — where there were no [has_homsets] assumptions, I’ve left things in terms of precategories.  But wherever there were explicit has_homsets assumptions, I’ve repackaged in terms of categories, and similar.  Like with UniMath/UniMath#1402, I think this was in many places a clear improvement in readability, and never a worsening.

Refactor to precategories to categories where appropriate

---

TypeTheory/Auxiliary/CategoryTheory.v
TypeTheory/RelUniv/RelUnivTransfer.v

This will be needed to restore compilation after merging PR 1532 of UniMath.

propagates correction of a misnamed construction

---

TypeTheory/Initiality/SyntacticCategory.v

therefore, checking of focused goals no longer applies, hence the file becomes immune against PR1582 of UniMath

no longer import the file from the PAdics package

---

.github/workflows/build-typetheory.yml

Maybe the build in CI fails because PACKAGES does not contain Tactics? I have not been able to reproduce it locally. I also opted to remove Bicategories and SubstitutionSystems because they do not seem used at all by TypeTheory.
Marking this as draft just to see if the CI runs and it makes a difference.

CI: Add Tactics and remove Bicategories and SubstitutionSystems.

---

TypeTheory/Articles/ALV_2017.v
TypeTheory/Articles/ALV_2018.v
TypeTheory/Auxiliary/ArrowCategory.v
TypeTheory/Auxiliary/CategoryTheory.v
TypeTheory/Auxiliary/CategoryTheoryImports.v
TypeTheory/Auxiliary/DisplayedCategories.v
TypeTheory/Auxiliary/Pullbacks.v
TypeTheory/Auxiliary/SetsAndPresheaves.v
TypeTheory/Auxiliary/TypeOfMorphisms.v
TypeTheory/Categories/category_FAM.v
TypeTheory/CompCats/FullyFaithfulDispFunctor.v
TypeTheory/CwF/CwF_def.v
TypeTheory/CwF/RepMaps.v
TypeTheory/CwF_TypeCat/CwF_SplitTypeCat_Defs.v
TypeTheory/CwF_TypeCat/TypeCat_Reassoc.v
TypeTheory/Initiality/Environments.v
TypeTheory/Initiality/Initiality.v
TypeTheory/Initiality/Interpretation.v
TypeTheory/Initiality/SyntacticCategory.v
TypeTheory/Initiality/SyntacticCategory_Structure.v
TypeTheory/Instances/Presheaves.v
TypeTheory/OtherDefs/CwF_Pitts_completion.v
TypeTheory/RelUniv/RelUnivTransfer.v
TypeTheory/RelUniv/RelUnivYonedaCompletion.v
TypeTheory/RelUniv/Transport_along_Equivs.v
TypeTheory/TypeCat/Contextual.v
TypeTheory/TypeCat/ExtraStructure.v

This removes the imports of UniMath.CategoryTheory.All from TypeTheory, based on the discussions in UniMath/UniMath#1589 and UniMath/UniMath#1588.

Remove some unnecessary imports.

---

TypeTheory/Initiality/InterpretationLemmas.v
TypeTheory/Initiality/SyntacticCategory.v

uses invmap(weqpathsinsetquot _ _ _) instead
is meant to resolve issue #225

replaces uses of setquotprpathsandR from PAdics

---

TypeTheory/Auxiliary/CategoryTheory.v
TypeTheory/CompCats/DiscreteComprehensionCat.v

Removes use of [univalenceweq] which is a duplicate of [univalence]. Also removes the scope [cat_deprecated]. This scope is essentially empty and unused in TypeTheory.

Small cleanup

---

TypeTheory/Csystems/hSet_ltowers.v
TypeTheory/Initiality/Interpretation.v
TypeTheory/Initiality/SyntacticCategory.v
TypeTheory/TypeCat/General.v
TypeTheory/TypeConstructions/CwF_SplitTypeCat_TypeEquiv.v

This fixes the build following https://github.com/UniMath/UniMath/pull/1643.
Two files remain to be updated:
- Initiality/Interpretation.v
- TypeCat/General.v
The rest is mostly changing `auto` to `apply idpath`.

Remove or make explicit dependency on coq.init.logic

---

.github/workflows/build-typetheory.yml
TypeTheory/CompCats/DiscreteComprehensionCat.v

TypeTheory breaks with recent coq-dev, reported upstream here: coq/coq#17461. 
This patch is a workaround.

Workaround coq bug.

---

Makefile
TypeTheory/.dir-locals.el
TypeTheory/Auxiliary/Auxiliary.v
TypeTheory/Auxiliary/CategoryTheoryImports.v
TypeTheory/Auxiliary/SetQuotients.v
TypeTheory/Categories/ess_alg_categories.v
TypeTheory/Csystems/prelim.v
TypeTheory/dune

Following UniMath/UniMath#1696, this replaces use of the `-type-in-type` flag (which was previously global for the repository, via the `Makefile` and `.dir-locals.el`) with an explicit `Export Unset Universe Checking` in `TypeTheory.Auxiliary.Auxiliary` and other root files of this development.
Summarising the positives and negatives from UniMath/UniMath#1696:
- one clear advantage — it allows potential per-file toggling of the option, so reducing which parts rely on type-in-type
- one questionable disadvantage — any repository importing this downstream may potentially inherit type-in-type (much less significant in `TypeTheory` than in `UniMath` itself)

Replace `-type-in-type` with `Unset Universe Checking`

---

TypeTheory/CwF_TypeCat/CwF_SplitTypeCat_Equiv_Cats.v
TypeTheory/Initiality/Interpretation.v
TypeTheory/TypeCat/General.v

Hi,
This patch removes the last two uses of Coq.Init.Logic from the TypeTheory repository. Thanks @benediktahrens for having a look.

#235: Remove dependency on Coq.Init.Logic

---

.github/workflows/build-typetheory.yml
dune-project

GitHub action v3 -> v4, Dune language 3.5 -> 3.8, Coq language 0.6 -> 0.8
